package com.billing.finalproject.entity;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "clients")
public class Client {
    public Client() {
        super();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Client ID is autogenerated")
    private Long clientId;

    @Schema(description = "Client Name", example = "Juan", requiredMode = Schema.RequiredMode.AUTO)
    private String clientName;

    @Schema(description = "Client Lastname", example = "Perez", requiredMode = Schema.RequiredMode.AUTO)
    private String clientLastname;

    @Schema(description = "Client Document Number", example = "12345678", requiredMode = Schema.RequiredMode.AUTO)
    private String docnumber;

    @JsonIgnore
    @OneToMany(mappedBy = "client", cascade = CascadeType.MERGE)
    private List<Invoice> invoices;

    public Client(Long id, String name, String lastname, String docnumber) {
        this.clientId = id;
        this.clientName = name;
        this.clientLastname = lastname;
        this.docnumber = docnumber;
    }

    public Long getClientId() {
        return clientId;
    }

    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientLastname() {
        return clientLastname;
    }

    public void setClientLastname(String clientLastname) {
        this.clientLastname = clientLastname;
    }

    public String getDocnumber() {
        return docnumber;
    }

    public void setDocnumber(String docnumber) {
        this.docnumber = docnumber;
    }

    public List<Invoice> getInvoices() {
        return invoices;
    }

    public void setInvoices(List<Invoice> invoices) {
        this.invoices = invoices;
    }

}
