package com.billing.finalproject.entity;

import java.util.Date;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

@Entity
@Table(name = "invoice")
public class Invoice {
    public Invoice() {
        super();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @Schema(description = "Invoice ID is autogenerated", hidden = true)
    private Long invoiceId;

    @Column(name = "create_at")
    @Schema(hidden = true)
    private java.sql.Date createdAt;

    @Column(name = "total")
    @Schema(description = "Total invoice price", example = "1000.00", hidden = true)
    private Double total;

    @Schema(description = "Total products in invoice", example = "2")
    @Column(name = "total_product")
    private int totalProduct;

    @ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "clientId")
    @Schema(description = "Client ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private Client client;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @Schema(description = "Invoice Details", requiredMode = Schema.RequiredMode.REQUIRED)
    private List<InvoiceDetails> invoiceDetails;

    public Invoice(Long id, Client client, java.sql.Date createdAt, double total, int totalProduct) {
        this.invoiceId = id;
        this.client = client;
        this.createdAt = createdAt;
        this.total = total;
        this.totalProduct = totalProduct;
    }

    public Long getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.sql.Date createdAt) {
        this.createdAt = createdAt;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public List<InvoiceDetails> getInvoiceDetails() {
        return invoiceDetails;
    }

    public void setInvoiceDetails(List<InvoiceDetails> invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }

    public void setTotalProduct(int totalProduct) {
        this.totalProduct = totalProduct;
    }

    public int getTotalProduct() {
        return totalProduct;
    }
}
